# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20161012_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='No Category', on_delete=django.db.models.deletion.SET_DEFAULT, to='listing.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
