# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20161012_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'TV Show'), ('M', 'Movie'), ('D', 'Documentary'), (None, 'No Category')], default=None, max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
